//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeDesginSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HdsInventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HdsInventory()
        {
            this.HdsOrderDetails = new HashSet<HdsOrderDetail>();
        }
    
        public int ID { get; set; }
        public string InventoryType { get; set; }
        public string VendorName { get; set; }
        public Nullable<int> InventoryLocationID { get; set; }
        public string ModelNumber { get; set; }
        public int SerialNumber { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> ListPrice { get; set; }
    
        public virtual HdsInventoryType HdsInventoryType { get; set; }
        public virtual HdsLocation HdsLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HdsOrderDetail> HdsOrderDetails { get; set; }
    }
}
