//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeDesginSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HdsOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HdsOrder()
        {
            this.HdsOrderDetails = new HashSet<HdsOrderDetail>();
        }
    
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public Nullable<System.DateTime> ProjectedFinishDate { get; set; }
        public string ActualFinishDate { get; set; }
        public Nullable<int> SalesAssociateID { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> Discounts { get; set; }
        public Nullable<decimal> TotalCommision { get; set; }
        public bool IsActive { get; set; }
    
        public virtual HdsCustomer HdsCustomer { get; set; }
        public virtual HdsEmployee HdsEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HdsOrderDetail> HdsOrderDetails { get; set; }
    }
}
