//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeDesginSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HdsOrderDetail
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public string InventoryTypeID { get; set; }
        public string VendorName { get; set; }
        public Nullable<int> SerialNumber { get; set; }
        public Nullable<int> InstallerID { get; set; }
        public Nullable<int> DeliveryID { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual HdsEmployee HdsEmployee { get; set; }
        public virtual HdsEmployee HdsEmployee1 { get; set; }
        public virtual HdsInventory HdsInventory { get; set; }
        public virtual HdsOrder HdsOrder { get; set; }
    }
}
