//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeDesginSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HdsVendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HdsVendor()
        {
            this.HdsInventoryTypes = new HashSet<HdsInventoryType>();
        }
    
        public int ID { get; set; }
        public string VendorName { get; set; }
        public string VendorStreetAddress { get; set; }
        public string VendorState { get; set; }
        public string VendorCity { get; set; }
        public Nullable<int> VendorZipCode { get; set; }
        public string VendorCountry { get; set; }
        public string VendorPhoneNumber { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HdsInventoryType> HdsInventoryTypes { get; set; }
    }
}
